### PR TITLE
fix: clean up authentication flow for bugs

### PR DESCRIPTION
**Pull request by Barissa-Imran**
- Change from using fetch to axios
- change to correct endpoints

### CODE REVIEW

**Review by KubasuIvanSakwa — APPROVED** [review]

**Comment by KubasuIvanSakwa** [comment]
merged by Ivan

**Comment by McRonaah** [comment]
also guys @Barissa-Imran  @KubasuIvanSakwa when you install new packages/dependenceis 
include the command to install the dependencies

**Comment by McRonaah** [comment]
So far Good work

**Comment by Barissa-Imran** [comment]
> also guys @Barissa-Imran  @KubasuIvanSakwa when you install new packages/dependenceis 
> include the command to install the dependencies 

Npm install

But noted

**Pull request merged**
